package study_1_4_1_error_exception;

import org.junit.runner.JUnitCore;

public class testCode {
    public static void main(String[] args) {
        JUnitCore.main("study_1_4_1_error_exception.UserDaoTest");
    }
}
